Neos:
  Imagine:
    driver: Imagick
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        charset: 'utf8mb4'
        host: db    		
        dbname: ${MYSQL_DATABASE}
        user: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}

